#!/usr/bin/python -O

"""
   get message from a qpid broker
"""
import sys, os
import time


import qpid.messaging.exceptions

import Amqp
from Amqp.RoutingKey import RoutingKey
from Amqp.QpidWrapper import ConsumerListener, Producer
from protomsg import GpbMessage


class Getter(ConsumerListener):
    """ class Getter """
    def __init__(self, broker, exchange, binding_keys,
                 output=sys.stdout,
                 brief=False, producer=None):
        super(Getter, self).__init__(broker, exchange, binding_keys)

        self.__broker = broker
        self.__output = output
        self.__brief = brief
        self.__producer = producer

        if __debug__:
            self.__force_output = True

        self.__exit = False


    def received(self, message):
        if message.subject:
            keystr = message.subject
        else:
            keystr = message.properties.get('x-amqp-0-10.routing-key')

        print 'Got:', keystr

        if self.__producer:
            self.__producer.send(keystr, message.content)

        if self.__brief:
            return

        if not message.content_type in ('application/x-protobuf',
                                    'application/octstream'):
            print message.content_type
            print 'Not a google protobuf message'
            return

        if self.__output != sys.stdout:
            self.__output.write('/@ routing key\n%s\n@/\n' % keystr)

        routingkey = RoutingKey(keystr)

        try:
            pmsg = GpbMessage(routingkey.package, routingkey.publication)
        except ImportError:
            self.__output.write('Unknown message {}'.format(routingkey))
            return


        from google.protobuf.message import DecodeError
        try:
            pmsg.loads(message.content)

            self.__output.write('{}'.format(pmsg))

            self.__output.write('@/\n\n')
            self.__output.flush()

        except DecodeError:
            print 'Decode error for key: %s' % keystr
            self.__output.write('Decode error for key: %s\n' % keystr)


# -- main start here --
def main():
    """ main function """
    from optparse import OptionParser
    parser = OptionParser()
    parser.add_option('-b', '--broker', dest = 'brokers', action='append',
          help='one or more address of the broker to subscribe')
    parser.add_option('-k', '--binding-key', dest = 'bindingKeys',
          action='append',
          help='routing keys to subscribe')
    parser.add_option('--proto-src', dest ='protoSrc', action='store',
          default = '../publications',
          help='directory to store subscribe, [default: %default]')
    parser.add_option('-o', '--output', dest ='out',
          action='store', default = sys.stdout,
          help='file to dump message text, [default: stdout]')
    parser.add_option('--forward',
          help='where to forward the publication')
    parser.add_option('--brief',
          action='store_true', default=False,
          help='only display routing key, [default: %default]')

    (opts, _args) = parser.parse_args()

    if opts.brokers is None:
        print 'Please specify brokers'
        parser.print_help()
        sys.exit(1)

    if __debug__:
        print opts.brokers
        print opts.bindingKeys

    exchange = 'amq.topic'

    if opts.out == sys.stdout:
        output = sys.stdout
    else:
        output = open(opts.out, 'w')

    Amqp.set_proto_src(opts.protoSrc)

    producer = Producer(opts.forward) if opts.forward else None

    getters = [Getter(broker, exchange, opts.bindingKeys,
                      output, opts.brief, producer)
                  for broker in opts.brokers]


    try:
        for getter in getters:
            getter.start()

        getter_alive = True
        while getter_alive:
            getter_alive = any(getter.is_alive() for getter in getters)

            time.sleep(5)
    except KeyboardInterrupt:
        print '\nControl-C pressed, exiting...'

    except qpid.messaging.exceptions.ConnectionError:
        print 'Lost connection, exit...'

    except qpid.messaging.exceptions.MalformedAddress:
        print 'Malformed routingkey'

    finally:
        for getter in getters:
            print 'Terminate', getter.name
            getter.stop()

    if output != sys.stdout:
        output.close()


if __name__ == '__main__':
    main()
